# conda environment description file for SalishSeaCmd package testing environment
#
# Creates a conda environment in which the SalishSeaCmd package unit tests and
# coverage analysis can be run.
# Primarily intended for creation of a docker image for use by bitbucket-pipelines.yml.

name: salishsea-cmd-test

channels:
  - conda-forge
  - defaults

dependencies:
  - arrow
  - attrs
  - cliff!=2.9.0
  - f90nml
  - python=3.7
  - pyyaml

  # For unit tests and coverage analysis
  - pytest
  - coverage

  - pip:
      - python-hglib
