# conda environment description file for SalishSeaCmd package testing environment
#
# Creates a conda environment in which the SalishSeaCmd package unit tests and
# coverage analysis can be run.
# Primarily intended for creation of a conda env for use in a GitHub Actions workflow.

name: salishsea-cmd-test

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - cliff
  - f90nml
  - gitpython
  - pip
  - pyyaml

  # For unit tests and coverage monitoring
  - coverage
  - pytest-cov

  # For documentation links checking
  - sphinx
  - sphinx_rtd_theme

  - pip:
    - python-hglib

    # For unit tests
    - pytest-randomly

    # Install NEMO-Cmd & SalishSeaCmd packages in editable mode
    - --editable git+https://github.com/SalishSeaCast/NEMO-Cmd.git#egg=NEMO-Cmd
    - --editable ../
