# conda environment description file for SalishSeaCmd package installation on HPC clusters
#
# Create a conda environment and install the `salishsea` command with:
#
#   $ conda env create -f SalishSeaCmd/envs/environment-hpc.yaml
#   $ conda activate salishsea-cmd
#   (salishsea-cmd)$ python -m pip install --user --editable NEMO-Cmd/
#   (salishsea-cmd)$ python -m pip install --user --editable SalishSeaCmd/

name: salishsea-cmd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - attrs
  - cliff
  - f90nml
  - gitpython
  - pip
  - python=3.13
  - pyyaml

  - pip:
    - python-hglib
