# conda environment description file for docs build envioronment
# on readthedocs.org
#
# This file is a union of the environment.yaml files in the
# SalishSeaCmd, SalishSeaNowcast, SalishSeaTools, and Marlin packages.

name: salishsea-cmd-rtd

channels:
  - defaults

dependencies:
  - python=3.7

  # RTD packages
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme
