# conda environment description file for SalishSeaCmd package
# development environment
#
# Create a conda environment in which the `salishsea` command can be run
# with:
#
#   $ conda env create -f SalishSeaCmd/environment.yaml
#   $ source activate salishsea-cmd
#   (salishsea-cmd)$ pip install --editable NEMO-Cmd/
#   (salishsea-cmd)$ pip install --editable SalishSeaCmd/
#
# The environment will also include all of the tools used to develop,
# test, and document the SalishSeaCmd package.
#
# See the requirements.txt file for an exhaustive list of all of the
# packages installed in the environment and their versions used in
# recent development.

name: salishsea-cmd

channels:
  - conda-forge
  - defaults

dependencies:
  - arrow
  - cliff!=2.9.0
  - f90nml
  - gitpython
  - pip
  - python>=3.5
  - pyyaml

  # For coding style
  - black
  # For unit tests
  - coverage
  - pytest

  # For documentation
  - sphinx
  - sphinx_rtd_theme

  - pip:
    - python-hglib
