name: sphinx-linkcheck

permissions: {}

on:
  push:
    branches: [ '*' ]
  schedule:
    - cron: 43 4 2 * *  # 04:43 UTC on the 2nd day of each month

jobs:
  sphinx-linkcheck:
    name: Sphinx linkcheck
    permissions:
      contents: read  # Required to access the repository's source code

    uses: UBC-MOAD/gha-workflows/.github/workflows/pixi-sphinx-linkcheck.yaml@main  # zizmor: ignore[unpinned-uses]
